Models/Pacient.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebApplication12.Models
{
    public class Pacient:ApplicationUser
    {
        [ForeignKey("Doctor")]
        public string DoctorId { get; set; }
        public virtual Doctor Doctor { get; set; }
        [ForeignKey("Diet")]
        public string DietId { get; set; }
        public int Age { get; set; }
        public string Alergic { get; set; }
        public DateTime CreationDate { get; set; }
        /// <summary>
        /// Diet duration in days interval
        /// </summary>
        public string Height { get; set; }
        public string Сontraindication { get; set; }
        public string Unlike { get; set; }
        public string LifeType { get; set; }
        public string StartWeight { get; set; }

        public int DietDurationDays { get; set; }
        public string CurrentDietName { get; set; }
        public int ConsultationCount { get; set; }
        public string TargetWeight { get; set; }
        public virtual Diet Diet { get; set; }
    }
}

Controllers/PacientsController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication12.DAL;
using WebApplication12.ViewModels;
using AutoMapper;
using System.Data.Entity.Validation;
using WebApplication12.Models;

namespace WebApplication11.Controllers
{
    public  class PacientsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Pacients
        public ActionResult Index(string searching)
        {
           
            var pacients = db.Pacients.ToList().Where(c => c.DoctorId == User.Identity.GetUserId());


            var search_pacient = pacients;
            if (searching == null) { }

                else
                search_pacient = pacients.Where(c => c.Name.Contains(searching)).ToList();



            var pacientVm = Mapper.Map<IEnumerable<PacientDetailsVm>>(search_pacient);
            return View(pacientVm);
            //return View()
        }
        public ActionResult Search(string searching)
        {
            return View(db.Pacients.Where(x=>x.Name.Contains(searching) || searching == null).ToList());
        }
        // GET: Pacients/Details/5
        public  ActionResult Details(string id)
        {
          


            var pacient = db.Pacients.FirstOrDefault(x => x.Id == id);




            var ls = db.DietMeals.Where(c => c.DietId == pacient.Diet.DietId).ToList();
            List<Meal> meals = new List<Meal>();


            foreach (var item in ls)
            {
                var it = db.Meals.Find(item.MealId);
                meals.Add(it);
            }
            pacient.Diet.Meals = meals;
            // pacient.Diet.Meals = db.Meals.Where(c=>c.DietId==pacient.Diet.DietId).ToList();

            var  pacientVM = Mapper.Map<PacientDetailsVm>(pacient);
            

            return View(pacientVM);

        }

       public ActionResult EditPacient(string id)
        {

            Pacient pacient = db.Pacients.Find(id);
            var pacientVM = Mapper.Map<PacientDetailsVm>(pacient);


            return View(pacientVM);    
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditPacient(PacientDetailsVm pacient)
        {

            Pacient pacien = new Pacient() ;
            pacien = db.Pacients.Find(pacient.Id);
            pacien.Height = pacient.Height;
            pacien.Age = pacient.Age;
            pacien.Unlike = pacient.Unlike;
            pacien.Alergic = pacient.Alergic;
            pacien.Сontraindication = pacient.EatNo;
            pacien.LifeType = pacient.LifeType;
            pacien.TargetWeight = pacient.TargetWeight;
            pacien.ConsultationCount = pacient.ConsultationCount;

            if (ModelState.IsValid)
            {
                db.Entry(pacien).State = EntityState.Modified;

                db.SaveChanges();
                return RedirectToAction("Details" , new { id = pacien.Id});
            }
           
            return View(pacient);
        }
        // GET: Pacients/Create
      

        // GET: Pacients/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pacient pacient = db.Pacients.Find(id);
            if (pacient == null)
            {
                return HttpNotFound();
            }
            return View(pacient);
        }

        // POST: Pacients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Surname,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName,DoctorId,CreationDate,DietDurationDays,CurrentDietName,ConsultationCount,TargetWeight")] Pacient pacient)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pacient).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pacient);
        }

        // GET: Pacients/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pacient pacient = db.Pacients.Find(id);
            if (pacient == null)
            {
                return HttpNotFound();
            }
            return View(pacient);
        }

        // POST: Pacients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Pacient pacient = db.Pacients.Find(id);
            db.Users.Remove(pacient);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Pacients/Create.cshtml
@model WebApplication12.Models.Pacient

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pacient</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailConfirmed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.EmailConfirmed)
                    @Html.ValidationMessageFor(model => model.EmailConfirmed, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PasswordHash, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PasswordHash, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PasswordHash, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SecurityStamp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SecurityStamp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SecurityStamp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumberConfirmed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.PhoneNumberConfirmed)
                    @Html.ValidationMessageFor(model => model.PhoneNumberConfirmed, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TwoFactorEnabled, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.TwoFactorEnabled)
                    @Html.ValidationMessageFor(model => model.TwoFactorEnabled, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LockoutEndDateUtc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LockoutEndDateUtc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LockoutEndDateUtc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LockoutEnabled, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.LockoutEnabled)
                    @Html.ValidationMessageFor(model => model.LockoutEnabled, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AccessFailedCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccessFailedCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccessFailedCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DoctorId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DoctorId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DoctorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DietDurationDays, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DietDurationDays, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DietDurationDays, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CurrentDietName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CurrentDietName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CurrentDietName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConsultationCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConsultationCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConsultationCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TargetWeight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TargetWeight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TargetWeight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Pacients/Delete.cshtml
@model WebApplication12.Models.Pacient

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

    

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pacient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailConfirmed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailConfirmed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PasswordHash)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PasswordHash)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecurityStamp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecurityStamp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumberConfirmed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumberConfirmed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TwoFactorEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TwoFactorEnabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LockoutEndDateUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LockoutEndDateUtc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LockoutEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LockoutEnabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccessFailedCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccessFailedCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DoctorId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoctorId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DietDurationDays)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DietDurationDays)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurrentDietName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrentDietName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConsultationCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConsultationCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TargetWeight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TargetWeight)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Pacients/Details.cshtml
@model WebApplication12.ViewModels.PacientDetailsVm

@{
    ViewBag.Title = "Karta Pacjenta";
}

<h2>Karta Pacjenta : @Model.Name @Model.SurName</h2>
<h4>Dieta : @Model.DietName@Html.ActionLink(HttpUtility.HtmlDecode("&#9998;"), "EditPacient", new { id = Model.Id })</h4>
<div>

    <div class="container">

        <div class="col-lg-2">
            <table class="table-condensed" id="t_draggable1">
                <thead>
                    <tr>
                        <th>Color</th>
                        <th>Meals</th>
                    </tr>
                </thead>
                <tbody class="t_sortable">
                    @foreach (var item in Model.Meals)
                    {
                        <tr>

                            <td class="one">color</td>
                            <td class="ui-widget-content">@item.Name</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="col-lg-4">

            <table class="table-bordered" id="t_draggable2">
                <tr>
                    <th>Time</th>
                    <th>Time for launch</th>
                    <th>Kolacja</th>
                </tr>
                <tbody class="t_sortable">
                    <tr>
                        <td></td>
                    </tr>
                    <tr class="one">
                        <td ></td>
                    </tr>
                    <tr>
                        <td class="timepicker"><input /></td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class=" col-lg-6">
        <h1>Karta pacjenta : @Model.Name @Model.SurName</h1>
        <h3>Dieta : @Model.DietName</h3>
        <p>Waga przy rozpoczeciu : @Model.StartWeight</p>
        <p>Waga docelowa : @Model.TargetWeight</p>  <p>Wzrost : @Model.Height</p>

        <p>Tryb zycia : @Model.LifeType</p>


        <p>Nie lubi : @Model.Unlike</p>
        <p>Alergia : @Model.Alergic</p>
        <p>Przeciwskazania : @Model.EatNo</p>


        <p>Liczba wizyt : @Model.ConsultationCount</p>


        <p>Email : <a>@Model.Email</a></p>



    </div>


        <style>
            #draggable {
                width: 10px;
                height: 10px;
                padding: 0.5em;
            }
        </style>



    </div>



@Scripts.Render("~/Scripts/jquery-3.3.1.min.js")
@Scripts.Render("~/bundles/jquery")
<script>
    $(document).ready(function () {
        var $tabs = $('#t_draggable2')
        $("tbody.t_sortable").sortable({
            connectWith: ".t_sortable"
             
        });
   
    var $tab_items = $tabs.droppable({
       
        drop: function (event, ui) {
            //$('input.timepicker').timepicker({
            //    timeFormat: 'h:mm p',
            //    interval: 60,
            //    minTime: '10',
            //    maxTime: '6:00pm',
            //    defaultTime: '11',
            //    startTime: '10:00',
            //    dynamic: false,
            //    dropdown: true,
            //    scrollbar: true
            //});
            return false;
        }
        });


    });
    
</script>

Views/Pacients/EditPacient.cshtml
@model WebApplication12.ViewModels.PacientDetailsVm

@{
    ViewBag.Title = "View";
}

<h2>View</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>PacientVm</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

  
    


    <div class="form-group">
        @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Alergic, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Alergic, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Alergic, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EatNo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EatNo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EatNo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Unlike, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Unlike, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Unlike, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LifeType, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LifeType, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LifeType, "", new { @class = "text-danger" })
        </div>
    </div>






    <div class="form-group">
        @Html.LabelFor(model => model.ConsultationCount, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ConsultationCount, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ConsultationCount, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TargetWeight, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TargetWeight, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TargetWeight, "", new { @class = "text-danger" })
        </div>
    </div>


   



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Pacients/Index.cshtml
@model IEnumerable<WebApplication12.ViewModels.PacientDetailsVm>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Add Pacient", "RegisterPacient", "Account")
</p>

@using (Html.BeginForm("Index","Pacients",FormMethod.Get))
{
    @Html.TextBox("searching") <input class="btn btn-success" type="submit" value="Index" />
}

<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>    
            Surname
        </th>
        <th>
            CreationDate
        </th>
        <th>
            DietDurationDays
        </th>
        <th>
            CurrentDietName
        </th>
        <th>
            ConsultationCount
        </th>
        <th>
            TargetWeight
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SurName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DietDurationDays)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.ConsultationCount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TargetWeight)
            </td>




            <td>
               
                @Html.ActionLink("Details", "Details",new{id = item.Id }) |
            </td>
        </tr>
    }

</table>